device: "auto"
train:
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
  - _target_: src.metrics.PESQ
    device: ${metrics.device}
    name: "PESQ"
  - _target_: src.metrics.SI_SNR
    device: ${metrics.device}
    name: "SI_SNR"
  - _target_: src.metrics.SI_SDR
    device: ${metrics.device}
    name: "SI_SDR"
inference:
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
  - _target_: src.metrics.PESQ
    device: ${metrics.device}
    name: "PESQ"
  - _target_: src.metrics.SI_SDR
    device: ${metrics.device}
    name: "SI_SDR"
  - _target_: src.metrics.SI_SNR
    device: ${metrics.device}
    name: "SI_SNR"