# src/configs/model/deepfilternet.yaml
_target_: src.model.DfNet

# верхнеуровневые флаги и состояние
run_df: true
train_mask: true

# параметры модели/DF (все дефолты)

# ModelParams
conv_lookahead: 0
conv_k_enc: 2
conv_k_dec: 1
conv_ch: 16
conv_width_f: 1
conv_dec_mode: transposed
conv_depthwise: true
convt_depthwise: true
emb_hidden_dim: 256
emb_num_layers: 1
df_hidden_dim: 256
df_num_layers: 3
gru_groups: 1
lin_groups: 1
group_shuffle: true
dfop_method: real_unfold
mask_pf: false
