defaults:
  - model: deepfilternet
  - writer: wandb
  - _self_

denoise:
  input_path: "/home/runtime57/hse/cw3/mine/data/df_noisy.wav"
  output_path: "data/denoised.wav"
  from_pretrained: "/home/runtime57/hse/cw3/mine/saved/fullrun/model_best.pth"
  device: auto
  seed: 1

stft:
  sr: 16000
  fft_size: 320
  hop_length: 160
  nb_erb: 24
  nb_df: 96
  norm_tau: 1
  lsnr_max: 35
  lsnr_min: -15
  min_nb_freqs: 1
  df_order: 5
  df_lookahead: 1
  pad_mode: input
