defaults:
  - model: deepfilternetgrnn.yaml
  - datasets: onebatch
  - dataloader: onebatch
  - transforms: example
  - _self_

evaluator:
  device_tensors: ["noisy", "clean"] 
  device: auto
  save_path: "model_metrics"
  seed: 1